package oracle

import (
	"fmt"

	go_ora "github.com/sijms/go-ora/v2"
)

// Config holds the connection fields the integration tests read from source.json; it
// duplicates the driver's Config connection fields.
//
// TODO: unify this with the driver config via autogenerated code from the proto definitions,
// instead of hand-maintaining a copy here.
type Config struct {
	Host             string            `json:"host"`
	Username         string            `json:"username"`
	Password         string            `json:"password"`
	ServiceName      string            `json:"service_name"`
	SID              string            `json:"sid"`
	Port             int               `json:"port"`
	SSLConfiguration *sslConfig        `json:"ssl"`
	JDBCURLParams    map[string]string `json:"jdbc_url_params"`
}

type sslConfig struct {
	Mode string `json:"mode,omitempty"`
}

func (c *Config) connectionString() string {
	urlOptions := make(map[string]string)
	for k, v := range c.JDBCURLParams {
		urlOptions[k] = v
	}
	if c.SID != "" {
		urlOptions["sid"] = c.SID
	}
	if c.SSLConfiguration != nil {
		if c.SSLConfiguration.Mode != "disable" {
			urlOptions["ssl"] = "true"
			urlOptions["ssl verify"] = "false"
		}
	}
	quotedUsername := fmt.Sprintf("%q", c.Username)
	return go_ora.BuildUrl(c.Host, c.Port, c.ServiceName, quotedUsername, c.Password, urlOptions)
}
