package testutils

import (
	"context"
	"os"
	"path"
	"path/filepath"
	"testing"
	"time"
)

const (
	icebergCatalog      = "olake_iceberg"
	sparkConnectAddress = "sc://localhost:15002"

	SyncTimeout                    = 10 * time.Minute
	BenchmarkThreshold             = 0.9
	maxRPSHistorySize              = 5
	kafkaRebalanceBulkMessageCount = int64(100_000)
)

type IntegrationTest struct {
	TestConfig                       *TestConfig
	ExpectedData                     map[string]interface{}
	ExpectedUpdatedData              map[string]interface{}
	DestinationDataTypeSchema        map[string]string
	UpdatedDestinationDataTypeSchema map[string]string
	DefaultCDCColumnsSchema          map[string]string
	Namespace                        string
	ExecuteQuery                     func(ctx context.Context, t *testing.T, streams []string, operation string, fileConfig bool)
	DestinationDB                    string
	CursorField                      string
	PartitionRegex                   string
	FilterConfig                     string
	ColumnToExclude                  string
}

type PerformanceTest struct {
	TestConfig      *TestConfig
	Namespace       string
	BackfillStreams []string
	CDCStreams      []string
	ExecuteQuery    func(ctx context.Context, t *testing.T, streams []string, operation string, fileConfig bool)
}

type SyncSpeed struct {
	Speed string `json:"Speed"`
}

type TestConfig struct {
	Driver        string
	DataFormat    string
	ImagePlatform string // overrides the base-image platform (e.g. linux/amd64 for db2 on arm hosts)

	// Host-side paths, read and written directly by the harness.
	HostRootPath            string // repo root, mounted at /test-olake and used to `make docker.base.build`
	HostTestDataPath        string // tests/<driver>/testdata[/<format>], bind-mounted at /test-olake/drivers/<driver>/internal/testdata in the container
	HostTestCatalogPath     string // expected test_streams.json
	HostCatalogPath         string // streams.json generated by discover / consumed by sync
	HostStatePath           string
	HostStateCheckpointPath string // backup of state.json used in 2PC recovery tests
	HostIcebergDestPath     string
	HostStatsPath           string
	BenchmarksPath          string

	// Container-side paths, passed as arguments to the olake binary.
	SourcePath             string
	CatalogPath            string
	IcebergDestinationPath string
	ParquetDestinationPath string
	StatePath              string
	StatsPath              string
}

// WithImagePlatform overrides the platform for the test container image. Useful for testing
// on different architectures (e.g. forcing linux/amd64 for db2 on an arm64 host).
func (t *TestConfig) WithImagePlatform(platform string) *TestConfig {
	t.ImagePlatform = platform
	return t
}

// GetTestConfig returns the test config for the given driver. It expects to be called from
// a test in tests/<driver>; extraParams[0] optionally selects a testdata sub-directory
// (e.g. kafka's "json"/"avro" formats).
func GetTestConfig(driver string, extraParams ...string) *TestConfig {
	// pwd is olake/tests/(driver)
	pwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	// root path is olake's root path
	rootPath := filepath.Join(pwd, "../..")
	dataFormat := ""
	if len(extraParams) > 0 {
		dataFormat = extraParams[0]
	}
	hostTestDataPath := filepath.Join(pwd, "testdata", dataFormat)
	hostPath := func(file string) string { return filepath.Join(hostTestDataPath, file) }
	// In-container the harness reads/writes testdata at the driver's canonical path; the
	// format-specific host dir is bind-mounted there (see runInTestContainer), so the format
	// sub-directory collapses onto this base path inside the container.
	containerTestDataDir := path.Join("/test-olake/drivers", driver, "internal", "testdata")
	containerPath := func(file string) string { return path.Join(containerTestDataDir, file) }
	return &TestConfig{
		Driver:                  driver,
		DataFormat:              dataFormat,
		HostRootPath:            rootPath,
		HostTestDataPath:        hostTestDataPath,
		HostTestCatalogPath:     hostPath("test_streams.json"),
		HostCatalogPath:         hostPath("streams.json"),
		HostStatePath:           hostPath("state.json"),
		HostStateCheckpointPath: hostPath("state_checkpoint.json"),
		HostIcebergDestPath:     hostPath("iceberg_destination.json"),
		HostStatsPath:           hostPath("stats.json"),
		BenchmarksPath:          hostPath("benchmarks.json"),
		SourcePath:              containerPath("source.json"),
		CatalogPath:             containerPath("streams.json"),
		IcebergDestinationPath:  containerPath("iceberg_destination.json"),
		ParquetDestinationPath:  containerPath("parquet_destination.json"),
		StatePath:               containerPath("state.json"),
		StatsPath:               containerPath("stats.json"),
	}
}
