package kafka

// Config holds the connection fields the integration tests read from source.json; it
// duplicates the driver's Config connection fields.
//
// TODO: unify this with the driver config via autogenerated code from the proto definitions,
// instead of hand-maintaining a copy here.
type Config struct {
	BootstrapServers string `json:"bootstrap_servers"`
}
