package db2

import "fmt"

// Config holds the connection fields the integration tests read from source.json; it
// duplicates the driver's Config connection fields.
//
// TODO: unify this with the driver config via autogenerated code from the proto definitions,
// instead of hand-maintaining a copy here.
type Config struct {
	Host             string            `json:"host"`
	Port             int               `json:"port"`
	Database         string            `json:"database"`
	Username         string            `json:"username"`
	Password         string            `json:"password"`
	JDBCURLParams    map[string]string `json:"jdbc_url_params"`
	SSLConfiguration *sslConfig        `json:"ssl"`
}

type sslConfig struct {
	Mode string `json:"mode,omitempty"`
}

// BuildDSN builds the go_ibm_db DSN from the source config. It mirrors the db2 driver's
// Config.BuildDSN so the tests connect exactly the way the driver does.
func (c *Config) BuildDSN() string {
	// Base DSN
	dsn := fmt.Sprintf(
		"HOSTNAME=%s;PORT=%d;DATABASE=%s;UID=%s;PWD=%s;",
		c.Host,
		c.Port,
		c.Database,
		c.Username,
		c.Password,
	)

	// JDBC-style params if provided
	for k, v := range c.JDBCURLParams {
		dsn += fmt.Sprintf(";%s=%s", k, v)
	}

	// SSL if enabled
	if c.SSLConfiguration != nil && c.SSLConfiguration.Mode != "disable" {
		dsn += ";SECURITY=SSL"
	}

	return dsn
}
