package mssql

// Config holds the connection fields the integration tests read from source.json; it
// duplicates the driver's Config connection fields.
//
// TODO: unify this with the driver config via autogenerated code from the proto definitions,
// instead of hand-maintaining a copy here.
type Config struct {
	Host     string `json:"host"`
	Port     int    `json:"port"`
	Database string `json:"database"`
	Username string `json:"username"`
	Password string `json:"password"`
}
